// opcode.h
//

#include "arith.h"
#include "io.h"
#include "string.h"
#include "eval.h"
#include "misc.h"
#include "bstruct.h"
#include "bvm.h"
#include "stack.h"
#include "introspect.h"
#include "hash.h"
#include "tptr.h"
#include "list.h"
#include "access.h"
#include "array.h"
#include "sexpr.h"
#include "logic.h"
#include "bpdl.h"
#include "bpdl2.h"


#ifndef OPCODE_H
#define OPCODE_H

#define NUM_INTERP_OPCODES 688

extern const babel_op opcode_array[NUM_INTERP_OPCODES];

// opcode 0 = DO NOT USE; bad pointers are a common bug and zero 
// memory is common; we want a bad code-pointer bug to manifest
// as quickly as possible, so opcode 0 is DO NOT USE

#define OPCODE_LIST \
    X(rsvd,           "rsvd",           OP_RSVD,        0x000)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x001)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x002)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x003)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x004)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x005)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x006)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x007)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x008)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x009)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x00a)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x00b)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x00c)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x00d)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x00e)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x00f)   \
    X(cadd_iod,       "cadd_iod",       OP_CADD_IOD,    0x010)   \
    X(rsvd,           "cadd_iop",       OP_CADD_IOP,    0x011)   \
    X(cadd_cod,       "cadd_iad",       OP_CADD_IAD,    0x012)   \
    X(rsvd,           "cadd_iap",       OP_CADD_IAP,    0x013)   \
    X(cadd_uod,       "cadd_uod",       OP_CADD_UOD,    0x014)   \
    X(rsvd,           "cadd_uop",       OP_CADD_UOP,    0x015)   \
    X(cadd_fod,       "cadd_fod",       OP_CADD_UAD,    0x016)   \
    X(rsvd,           "cadd_uap",       OP_CADD_UAP,    0x017)   \
    X(csub_iod,       "csub_iod",       OP_CSUB_IOD,    0x018)   \
    X(rsvd,           "csub_iop",       OP_CSUB_IOP,    0x019)   \
    X(rsvd,           "csub_iad",       OP_CSUB_IAD,    0x01a)   \
    X(rsvd,           "csub_iap",       OP_CSUB_IAP,    0x01b)   \
    X(csub_uod,       "csub_uod",       OP_CSUB_UOD,    0x01c)   \
    X(rsvd,           "csub_uop",       OP_CSUB_UOP,    0x01d)   \
    X(rsvd,           "csub_fod",       OP_CSUB_UAD,    0x01e)   \
    X(rsvd,           "csub_uap",       OP_CSUB_UAP,    0x01f)   \
    X(cmul_iod,       "cmul_iod",       OP_CMUL_IOD,    0x020)   \
    X(rsvd,           "cmul_iop",       OP_CMUL_IOP,    0x021)   \
    X(rsvd,           "cmul_iad",       OP_CMUL_IAD,    0x022)   \
    X(rsvd,           "cmul_iap",       OP_CMUL_IAP,    0x023)   \
    X(cmul_uod,       "cmul_uod",       OP_CMUL_UOD,    0x024)   \
    X(rsvd,           "cmul_uop",       OP_CMUL_UOP,    0x025)   \
    X(rsvd,           "cmul_fod",       OP_CMUL_UAD,    0x026)   \
    X(rsvd,           "cmul_uap",       OP_CMUL_UAP,    0x027)   \
    X(cdiv_iod,       "cdiv_iod",       OP_CDIV_IOD,    0x028)   \
    X(rsvd,           "cdiv_iop",       OP_CDIV_IOP,    0x029)   \
    X(rsvd,           "cdiv_iad",       OP_CDIV_IAD,    0x02a)   \
    X(rsvd,           "cdiv_iap",       OP_CDIV_IAP,    0x02b)   \
    X(cdiv_uod,       "cdiv_uod",       OP_CDIV_UOD,    0x02c)   \
    X(rsvd,           "cdiv_uop",       OP_CDIV_UOP,    0x02d)   \
    X(rsvd,           "cdiv_fod",       OP_CDIV_UAD,    0x02e)   \
    X(rsvd,           "cdiv_uap",       OP_CDIV_UAP,    0x02f)   \
    X(cabs_iod,       "cabs_iod",       OP_CABS_IOD,    0x030)   \
    X(rsvd,           "cabs_iop",       OP_CABS_IOP,    0x031)   \
    X(rsvd,           "cabs_iad",       OP_CABS_IAD,    0x032)   \
    X(rsvd,           "cabs_iap",       OP_CABS_IAP,    0x033)   \
    X(rsvd,           "cabs_uod",       OP_CABS_UOD,    0x034)   \
    X(rsvd,           "cabs_uop",       OP_CABS_UOP,    0x035)   \
    X(rsvd,           "cabs_uad",       OP_CABS_UAD,    0x036)   \
    X(rsvd,           "cabs_uap",       OP_CABS_UAP,    0x037)   \
    X(crem_iod,       "crem_iod",       OP_CREM_IOD,    0x038)   \
    X(rsvd,           "crem_iop",       OP_CREM_IOP,    0x039)   \
    X(rsvd,           "crem_iad",       OP_CREM_IAD,    0x03a)   \
    X(rsvd,           "crem_iap",       OP_CREM_IAP,    0x03b)   \
    X(crem_uod,       "crem_uod",       OP_CREM_UOD,    0x03c)   \
    X(rsvd,           "crem_uop",       OP_CREM_UOP,    0x03d)   \
    X(rsvd,           "crem_uad",       OP_CREM_UAD,    0x03e)   \
    X(rsvd,           "crem_uap",       OP_CREM_UAP,    0x03f)   \
    X(cshl_uod,       "cshl_uod",       OP_CSHL_UOD,    0x040)   \
    X(rsvd,           "cshl_uop",       OP_CSHL_UOP,    0x041)   \
    X(rsvd,           "cshl_uad",       OP_CSHL_UAD,    0x042)   \
    X(rsvd,           "cshl_uap",       OP_CSHL_UAP,    0x043)   \
    X(crol_uod,       "crol_uod",       OP_CROL_UOD,    0x044)   \
    X(rsvd,           "crol_uop",       OP_CROL_UOP,    0x045)   \
    X(rsvd,           "crol_uad",       OP_CROL_UAD,    0x046)   \
    X(rsvd,           "crol_uap",       OP_CROL_UAP,    0x047)   \
    X(cshr_uod,       "cshr_uod",       OP_CSHR_UOD,    0x048)   \
    X(rsvd,           "cshr_uop",       OP_CSHR_UOP,    0x049)   \
    X(rsvd,           "cshr_uad",       OP_CSHR_UAD,    0x04a)   \
    X(rsvd,           "cshr_uap",       OP_CSHR_UAP,    0x04b)   \
    X(cshr_iod,       "cshr_iod",       OP_CSHR_IOD,    0x04c)   \
    X(rsvd,           "cshr_iop",       OP_CSHR_IOP,    0x04d)   \
    X(rsvd,           "cshr_iad",       OP_CSHR_IAD,    0x04e)   \
    X(rsvd,           "cshr_iap",       OP_CSHR_IAP,    0x04f)   \
    X(logicF0_od,     "logicF0_od",     OP_LOGICF0_OD,  0x050)   \
    X(rsvd,           "logicF0_op",     OP_LOGICF0_OP,  0x051)   \
    X(rsvd,           "logicF0_ad",     OP_LOGICF0_AD,  0x052)   \
    X(rsvd,           "logicF0_ap",     OP_LOGICF0_AP,  0x053)   \
    X(logicF1_od,     "logicF1_od",     OP_LOGICF1_OD,  0x054)   \
    X(rsvd,           "logicF1_op",     OP_LOGICF1_OP,  0x055)   \
    X(rsvd,           "logicF1_ad",     OP_LOGICF1_AD,  0x056)   \
    X(rsvd,           "logicF1_ap",     OP_LOGICF1_AP,  0x057)   \
    X(logicF2_od,     "logicF2_od",     OP_LOGICF2_OD,  0x058)   \
    X(rsvd,           "logicF2_op",     OP_LOGICF2_OP,  0x059)   \
    X(rsvd,           "logicF2_ad",     OP_LOGICF2_AD,  0x05a)   \
    X(rsvd,           "logicF2_ap",     OP_LOGICF2_AP,  0x05b)   \
    X(logicF3_od,     "logicF3_od",     OP_LOGICF3_OD,  0x05c)   \
    X(rsvd,           "logicF3_op",     OP_LOGICF3_OP,  0x05d)   \
    X(rsvd,           "logicF3_ad",     OP_LOGICF3_AD,  0x05e)   \
    X(rsvd,           "logicF3_ap",     OP_LOGICF3_AP,  0x05f)   \
    X(logicF4_od,     "logicF4_od",     OP_LOGICF4_OD,  0x060)   \
    X(rsvd,           "logicF4_op",     OP_LOGICF4_OP,  0x061)   \
    X(rsvd,           "logicF4_ad",     OP_LOGICF4_AD,  0x062)   \
    X(rsvd,           "logicF4_ap",     OP_LOGICF4_AP,  0x063)   \
    X(logicF5_od,     "logicF5_od",     OP_LOGICF5_OD,  0x064)   \
    X(rsvd,           "logicF5_op",     OP_LOGICF5_OP,  0x065)   \
    X(rsvd,           "logicF5_ad",     OP_LOGICF5_AD,  0x066)   \
    X(rsvd,           "logicF5_ap",     OP_LOGICF5_AP,  0x067)   \
    X(logicF6_od,     "logicF6_od",     OP_LOGICF6_OD,  0x068)   \
    X(rsvd,           "logicF6_op",     OP_LOGICF6_OP,  0x069)   \
    X(rsvd,           "logicF6_ad",     OP_LOGICF6_AD,  0x06a)   \
    X(rsvd,           "logicF6_ap",     OP_LOGICF6_AP,  0x06b)   \
    X(logicF7_od,     "logicF7_od",     OP_LOGICF7_OD,  0x06c)   \
    X(rsvd,           "logicF7_op",     OP_LOGICF7_OP,  0x06d)   \
    X(rsvd,           "logicF7_ad",     OP_LOGICF7_AD,  0x06e)   \
    X(rsvd,           "logicF7_ap",     OP_LOGICF7_AP,  0x06f)   \
    X(logicF8_od,     "logicF8_od",     OP_LOGICF8_OD,  0x070)   \
    X(rsvd,           "logicF8_op",     OP_LOGICF8_OP,  0x071)   \
    X(rsvd,           "logicF8_ad",     OP_LOGICF8_AD,  0x072)   \
    X(rsvd,           "logicF8_ap",     OP_LOGICF8_AP,  0x073)   \
    X(logicF9_od,     "logicF9_od",     OP_LOGICF9_OD,  0x074)   \
    X(rsvd,           "logicF9_op",     OP_LOGICF9_OP,  0x075)   \
    X(rsvd,           "logicF9_ad",     OP_LOGICF9_AD,  0x076)   \
    X(rsvd,           "logicF9_ap",     OP_LOGICF9_AP,  0x077)   \
    X(logicFa_od,     "logicFa_od",     OP_LOGICFA_OD,  0x078)   \
    X(rsvd,           "logicFa_op",     OP_LOGICFA_OP,  0x079)   \
    X(rsvd,           "logicFa_ad",     OP_LOGICFA_AD,  0x07a)   \
    X(rsvd,           "logicFa_ap",     OP_LOGICFA_AP,  0x07b)   \
    X(logicFb_od,     "logicFb_od",     OP_LOGICFB_OD,  0x07c)   \
    X(rsvd,           "logicFb_op",     OP_LOGICFB_OP,  0x07d)   \
    X(rsvd,           "logicFb_ad",     OP_LOGICFB_AD,  0x07e)   \
    X(rsvd,           "logicFb_ap",     OP_LOGICFB_AP,  0x07f)   \
    X(logicFc_od,     "logicFc_od",     OP_LOGICFC_OD,  0x080)   \
    X(rsvd,           "logicFc_op",     OP_LOGICFC_OP,  0x081)   \
    X(rsvd,           "logicFc_ad",     OP_LOGICFC_AD,  0x082)   \
    X(rsvd,           "logicFc_ap",     OP_LOGICFC_AP,  0x083)   \
    X(logicFd_od,     "logicFd_od",     OP_LOGICFD_OD,  0x084)   \
    X(rsvd,           "logicFd_op",     OP_LOGICFD_OP,  0x085)   \
    X(rsvd,           "logicFd_ad",     OP_LOGICFD_AD,  0x086)   \
    X(rsvd,           "logicFd_ap",     OP_LOGICFD_AP,  0x087)   \
    X(logicFe_od,     "logicFe_od",     OP_LOGICFE_OD,  0x088)   \
    X(rsvd,           "logicFe_op",     OP_LOGICFE_OP,  0x089)   \
    X(rsvd,           "logicFe_ad",     OP_LOGICFE_AD,  0x08a)   \
    X(rsvd,           "logicFe_ap",     OP_LOGICFE_AP,  0x08b)   \
    X(logicFf_od,     "logicFf_od",     OP_LOGICFF_OD,  0x08c)   \
    X(rsvd,           "logicFf_op",     OP_LOGICFF_OP,  0x08d)   \
    X(rsvd,           "logicFf_ad",     OP_LOGICFF_AD,  0x08e)   \
    X(rsvd,           "logicFf_ap",     OP_LOGICFF_AP,  0x08f)   \
    X(cnot_od,        "cnot_od",        OP_CNOT_OD,     0x090)   \
    X(rsvd,           "rsvd",           OP_CNOT_OP,     0x091)   \
    X(rsvd,           "rsvd",           OP_CNOT_AD,     0x092)   \
    X(rsvd,           "rsvd",           OP_CNOT_AP,     0x093)   \
    X(rsvd,           "rsvd",           OP_AND_OD,      0x094)   \
    X(rsvd,           "rsvd",           OP_AND_OP,      0x095)   \
    X(rsvd,           "rsvd",           OP_AND_AD,      0x096)   \
    X(rsvd,           "rsvd",           OP_AND_AP,      0x097)   \
    X(not_d,          "not_d",          OP_OR_OD,       0x098)   \
    X(rsvd,           "not_p",          OP_OR_OP,       0x099)   \
    X(and_d,          "and_d",          OP_OR_AD,       0x09a)   \
    X(rsvd,           "and_p",          OP_OR_AP,       0x09b)   \
    X(or_d,           "or_d",           OP_NOT_OD,      0x09c)   \
    X(rsvd,           "or_p",           OP_NOT_OP,      0x09d)   \
    X(xor_d,          "xor_d",          OP_NOT_AD,      0x09e)   \
    X(rsvd,           "xor_p",          OP_NOT_AP,      0x09f)   \
    X(rsvd,           "clt_uod",        OP_CLT_UOD,     0x0a0)   \
    X(rsvd,           "clt_uop",        OP_CLT_UOP,     0x0a1)   \
    X(rsvd,           "clt_uad",        OP_CLT_UAD,     0x0a2)   \
    X(rsvd,           "clt_uap",        OP_CLT_UAP,     0x0a3)   \
    X(clt_iod,        "clt_iod",        OP_CLT_IOD,     0x0a4)   \
    X(rsvd,           "clt_iop",        OP_CLT_IOP,     0x0a5)   \
    X(rsvd,           "clt_iad",        OP_CLT_IAD,     0x0a6)   \
    X(rsvd,           "clt_iap",        OP_CLT_IAP,     0x0a7)   \
    X(rsvd,           "cle_uod",        OP_CLE_UOD,     0x0a8)   \
    X(rsvd,           "cle_uop",        OP_CLE_UOP,     0x0a9)   \
    X(rsvd,           "cle_uad",        OP_CLE_UAD,     0x0aa)   \
    X(rsvd,           "cle_uap",        OP_CLE_UAP,     0x0ab)   \
    X(cle_iod,        "cle_iod",        OP_CLE_IOD,     0x0ac)   \
    X(rsvd,           "cle_iop",        OP_CLE_IOP,     0x0ad)   \
    X(rsvd,           "cle_iad",        OP_CLE_IAD,     0x0ae)   \
    X(rsvd,           "cle_iap",        OP_CLE_IAP,     0x0af)   \
    X(rsvd,           "cgt_uod",        OP_CGT_UOD,     0x0b0)   \
    X(rsvd,           "cgt_uop",        OP_CGT_UOP,     0x0b1)   \
    X(rsvd,           "cgt_uad",        OP_CGT_UAD,     0x0b2)   \
    X(rsvd,           "cgt_uap",        OP_CGT_UAP,     0x0b3)   \
    X(cgt_iod,        "cgt_iod",        OP_CGT_IOD,     0x0b4)   \
    X(rsvd,           "cgt_iop",        OP_CGT_IOP,     0x0b5)   \
    X(rsvd,           "cgt_iad",        OP_CGT_IAD,     0x0b6)   \
    X(rsvd,           "cgt_iap",        OP_CGT_IAP,     0x0b7)   \
    X(rsvd,           "cge_uod",        OP_CGE_UOD,     0x0b8)   \
    X(rsvd,           "cge_uop",        OP_CGE_UOP,     0x0b9)   \
    X(rsvd,           "cge_uad",        OP_CGE_UAD,     0x0ba)   \
    X(rsvd,           "cge_uap",        OP_CGE_UAP,     0x0bb)   \
    X(cge_iod,        "cge_iod",        OP_CGE_IOD,     0x0bc)   \
    X(rsvd,           "cge_iop",        OP_CGE_IOP,     0x0bd)   \
    X(rsvd,           "cge_iad",        OP_CGE_IAD,     0x0be)   \
    X(rsvd,           "cge_iap",        OP_CGE_IAP,     0x0bf)   \
    X(cne_od,         "cne_od",         OP_CNE_OD,      0x0c0)   \
    X(rsvd,           "cne_op",         OP_CNE_OP,      0x0c1)   \
    X(rsvd,           "cne_ad",         OP_CNE_AD,      0x0c2)   \
    X(rsvd,           "cne_ap",         OP_CNE_AP,      0x0c3)   \
    X(ceq_od,         "ceq_od",         OP_CEQ_OD,      0x0c4)   \
    X(rsvd,           "ceq_op",         OP_CEQ_OP,      0x0c5)   \
    X(rsvd,           "ceq_ad",         OP_CEQ_AD,      0x0c6)   \
    X(rsvd,           "ceq_ap",         OP_CEQ_AP,      0x0c7)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0c8)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0c9)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0ca)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0cb)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0cc)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0cd)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0ce)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0cf)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0d0)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0d1)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0d2)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0d3)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0d4)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0d5)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0d6)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0d7)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0d8)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0d9)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0da)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0db)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0dc)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0dd)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0de)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0df)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0e0)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0e1)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0e2)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0e3)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0e4)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0e5)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0e6)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0e7)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0e8)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0e9)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0ea)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0eb)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0ec)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0ed)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0ee)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0ef)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0f0)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0f1)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0f2)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0f3)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0f4)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0f5)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0f6)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0f7)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0f8)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0f9)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0fa)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0fb)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0fc)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0fd)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0fe)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x0ff)   \
    X(dup,            "dup",            OP_DUP,         0x100)   \
    X(zap,            "zap",            OP_ZAP,         0x101)   \
    X(swap,           "swap",           OP_SWAP,        0x102)   \
    X(sel,            "sel",            OP_SEL,         0x103)   \
    X(flip,           "flip",           OP_FLIP,        0x104)   \
    X(rot,            "rot",            OP_ROT,         0x105)   \
    X(twist,          "twist",          OP_TWIST,       0x106)   \
    X(up,             "up",             OP_UP,          0x107)   \
    X(down,           "down",           OP_DOWN,        0x108)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x109)   \
    X(rsvd,           "put",            OP_PUT,         0x10a)   \
    X(bottom,         "bottom",         OP_BOTTOM,      0x10b)   \
    X(rsvd,           "top",            OP_TOP,         0x10c)   \
    X(depth,          "depth",          OP_DEPTH,       0x10d)   \
    X(dia,            "dia",            OP_DIA,         0x10e)   \
    X(clear,          "clear",          OP_CLEAR,       0x10f)   \
    X(nest,           "nest",           OP_NEST,        0x110)   \
    X(give,           "give",           OP_GIVE,        0x111)   \
    X(take,           "take",           OP_TAKE,        0x112)   \
    X(selr,           "selr",           OP_SELR,        0x113)   \
    X(stack_save_op,  "stack_save",     OP_RSVD,        0x114)   \
    X(stack_restore_op, "stack_restore", OP_RSVD,       0x115)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x116)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x117)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x118)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x119)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x11a)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x11b)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x11c)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x11d)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x11e)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x11f)   \
    X(msize_d,        "msize_d",        OP_MSIZE_D,     0x120)   \
    X(rsvd,           "msize_p",        OP_MSIZE_P,     0x121)   \
    X(sfield_d,       "sfield_d",       OP_SFIELD_D,    0x122)   \
    X(rsvd,           "sfield_p",       OP_SFIELD_P,    0x123)   \
    X(mu_d,           "mu_d",           OP_MU_D,        0x124)   \
    X(rsvd,           "mu_p",           OP_MU_P,        0x125)   \
    X(nva_d,          "nva_d",          OP_NVA_D,       0x126)   \
    X(rsvd,           "nva_p",          OP_NVA_P,       0x127)   \
    X(npt_d,          "npt_d",          OP_NPT_D,       0x128)   \
    X(rsvd,           "npt_p",          OP_NPT_P,       0x129)   \
    X(nlf_d,          "nlf_d",          OP_NLF_D,       0x12a)   \
    X(rsvd,           "nlf_p",          OP_NLF_P,       0x12b)   \
    X(nin_d,          "nin_d",          OP_NIN_D,       0x12c)   \
    X(rsvd,           "nin_p",          OP_NIN_P,       0x12d)   \
    X(isval_d,        "isval_d",        OP_ISVAL_D,     0x12e)   \
    X(rsvd,           "isval_p",        OP_ISVAL_P,     0x12f)   \
    X(isptr_d,        "isptr_d",        OP_ISPTR_D,     0x130)   \
    X(rsvd,           "isptr_p",        OP_ISPTR_P,     0x131)   \
    X(istag_d,        "istag_d",        OP_ISTAG_D,     0x132)   \
    X(rsvd,           "istag_p",        OP_ISTAG_P,     0x133)   \
    X(span_d,         "span_d",         OP_SPAN_D,      0x134)   \
    X(rsvd,           "span_p",         OP_SPAN_P,      0x135)   \
    X(load_d,         "load_d",         OP_LOAD_D,      0x136)   \
    X(rsvd,           "load_p",         OP_LOAD_P,      0x137)   \
    X(unload_d,       "unload_d",       OP_UNLOAD_D,    0x138)   \
    X(rsvd,           "unload_p",       OP_UNLOAD_P,    0x139)   \
    X(cp_d,           "cp_d",           OP_CP_D,        0x13a)   \
    X(rsvd,           "cp_p",           OP_CP_P,        0x13b)   \
    X(bs2gv_d,        "bs2gv_d",        OP_BS2GV_D,     0x13c)   \
    X(rsvd,           "bs2gv_p",        OP_BS2GV_P,     0x13d)   \
    X(bs2str_d,       "bs2str_d",       OP_BS2STR_D,    0x13e)   \
    X(rsvd,           "bs2str_p",       OP_BS2STR_P,    0x13f)   \
    X(newptr_d,       "newptr_d",       OP_NEWPTR_D,    0x140)   \
    X(rsvd,           "newptr_p",       OP_NEWPTR_P,    0x141)   \
    X(newval_d,       "newval_d",       OP_NEWVAL_D,    0x142)   \
    X(rsvd,           "newval_p",       OP_NEWVAL_P,    0x143)   \
    X(newtag_d,       "newtag_d",       OP_NEWTAG_D,    0x144)   \
    X(rsvd,           "newtag_p",       OP_NEWTAG_P,    0x145)   \
    X(detag_d,        "detag_d",        OP_DETAG_D,     0x146)   \
    X(rsvd,           "detag_p",        OP_DETAG_P,     0x147)   \
    X(get_tag_d,      "get_tag_d",      OP_GET_TAG_D,   0x148)   \
    X(rsvd,           "get_tag_p",      OP_GET_TAG_P,   0x149)   \
    X(tageq_d,        "tageq_d",        OP_TAGEQ_D,     0x14a)   \
    X(rsvd,           "tageq_p",        OP_TAGEQ_P,     0x14b)   \
    X(is_nilop,       "is_nil",         OP_IS_NIL,      0x14c)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x14d)   \
    X(is_falseop,     "is_false",       OP_IS_FALSE,    0x14e)   \
    X(is_trueop,      "is_true",        OP_IS_TRUE,     0x14f)   \
    X(is_rejectop,    "is_reject",      OP_IS_REJECT,   0x150)   \
    X(is_acceptop,    "is_accept",      OP_IS_ACCEPT,   0x151)   \
    X(ntag_d,         "ntag_d",         OP_RSVD,        0x152)   \
    X(bs2str2_d,      "bs2str2_d",      OP_BS2STR2_D,   0x153)   \
    X(rsvd,           "bs2str2_p",      OP_BS2STR2_P,   0x154)   \
    X(semicolon,      "semicolon",      OP_RSVD,        0x155)   \
    X(replace_d,      "replace_d",      OP_REPLACE_D,   0x156)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x157)   \
    X(find_tag_d,     "find_tag_d",     OP_RSVD,        0x158)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x159)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x15a)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x15b)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x15c)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x15d)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x15e)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x15f)   \
    X(th_rmd,         "th_rmd",         OP_TH_RMD,      0x160)   \
    X(th_wmp,         "th_wmp",         OP_TH_WMP,      0x161)   \
    X(th_r8d,         "th_r8d",         OP_TH_R8D,      0x162)   \
    X(rsvd,           "th_w8p",         OP_TH_W8P,      0x163)   \
    X(rsvd,           "th_r1d",         OP_TH_R1D,      0x164)   \
    X(rsvd,           "th_w1p",         OP_TH_W1P,      0x165)   \
    X(move_md,        "move_md",        OP_MOVE_MD,     0x166)   \
    X(rsvd,           "move_mp",        OP_MOVE_MP,     0x167)   \
    X(move_8d,        "move_8d",        OP_MOVE_8D,     0x168)   \
    X(rsvd,           "move_8p",        OP_MOVE_8P,     0x169)   \
    X(rsvd,           "move_1d",        OP_MOVE_1D,     0x16a)   \
    X(rsvd,           "move_1p",        OP_MOVE_1P,     0x16b)   \
    X(rsvd,           "paste_md",       OP_PASTE_MD,    0x16c)   \
    X(rsvd,           "paste_mp",       OP_PASTE_MP,    0x16d)   \
    X(rsvd,           "paste_8d",       OP_PASTE_8D,    0x16e)   \
    X(rsvd,           "paste_8p",       OP_PASTE_8P,    0x16f)   \
    X(rsvd,           "paste_1d",       OP_PASTE_1D,    0x170)   \
    X(rsvd,           "paste_1p",       OP_PASTE_1P,    0x171)   \
    X(arlen_md,       "arlen_md",       OP_ARLEN_MD,    0x172)   \
    X(rsvd,           "arlen_mp",       OP_ARLEN_MP,    0x173)   \
    X(arlen_8d,       "arlen_8d",       OP_ARLEN_8D,    0x174)   \
    X(rsvd,           "arlen_8p",       OP_ARLEN_8P,    0x175)   \
    X(rsvd,           "arlen_1d",       OP_ARLEN_1D,    0x176)   \
    X(rsvd,           "arlen_1p",       OP_ARLEN_1P,    0x177)   \
    X(cat_md,         "cat_md",         OP_CAT_MD,      0x178)   \
    X(rsvd,           "cat_mp",         OP_CAT_MP,      0x179)   \
    X(cat_8d,         "cat_8d",         OP_CAT_8D,      0x17a)   \
    X(rsvd,           "cat_8p",         OP_CAT_8P,      0x17b)   \
    X(rsvd,           "cat_1d",         OP_CAT_1D,      0x17c)   \
    X(rsvd,           "cat_1p",         OP_CAT_1P,      0x17d)   \
    X(slice_md,       "slice_md",       OP_SLICE_MD,    0x17e)   \
    X(rsvd,           "slice_mp",       OP_SLICE_MP,    0x17f)   \
    X(slice_8d,       "slice_8d",       OP_SLICE_8D,    0x180)   \
    X(rsvd,           "slice_8p",       OP_SLICE_8P,    0x181)   \
    X(rsvd,           "slice_1d",       OP_SLICE_1D,    0x182)   \
    X(rsvd,           "slice_1p",       OP_SLICE_1P,    0x183)   \
    X(arcmp_md,       "arcmp_md",       OP_ARCMP_MD,    0x184)   \
    X(rsvd,           "arcmp_mp",       OP_ARCMP_MP,    0x185)   \
    X(arcmp_8d,       "arcmp_8d",       OP_ARCMP_8D,    0x186)   \
    X(rsvd,           "arcmp_8p",       OP_ARCMP_8P,    0x187)   \
    X(strcmp_md,      "strcmp_md",      OP_STRCMP_MD,   0x188)   \
    X(rsvd,           "arcmp_1p",       OP_ARCMP_1P,    0x189)   \
    X(strcmp_8d,      "strcmp_8d",      OP_STRCMP_8D,   0x18a)   \
    X(rsvd,           "cut_mp",         OP_CUT_MP,      0x18b)   \
    X(rsvd,           "strmatch_md",    OP_STRMATCH_MD, 0x18c)   \
    X(rsvd,           "cut_8p",         OP_CUT_8P,      0x18d)   \
    X(strmatch_8d,    "strmatch_8d",    OP_STRMATCH_MD, 0x18e)   \
    X(rsvd,           "cut_1p",         OP_CUT_1P,      0x18f)   \
    X(rsvd,           "trunc_d",        OP_TRUNC_D,     0x190)   \
    X(rsvd,           "trunc_p",        OP_TRUNC_P,     0x191)   \
    X(ar2ls_d,        "ar2ls_d",        OP_AR2LS_D,     0x192)   \
    X(rsvd,           "ar2ls_p",        OP_AR2LS_P,     0x193)   \
    X(ar2str_d,       "ar2str_d",       OP_AR2STR_D,    0x194)   \
    X(rsvd,           "ar2str_p",       OP_AR2STR_P,    0x195)   \
    X(merge_sort_d,   "merge_sort_d",   OP_MERGE_SORT_D, 0x196)   \
    X(rsvd,           "shuf_p",         OP_SHUF_P,      0x197)   \
    X(rsvd,           "sortval_d",      OP_SORTVAL_D,   0x198)   \
    X(rsvd,           "sortlf_p",       OP_SORTLF_P,    0x199)   \
    X(get,            "get",            OP_GET,         0x19a)   \
    X(set,            "set",            OP_SET,         0x19b)   \
    X(get2,           "get2",           OP_GET2,        0x19c)   \
    X(set2,           "set2",           OP_SET2,        0x19d)   \
    X(bscmp_d,        "bscmp_d",        OP_RSVD,        0x19e)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x19f)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1a0)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1a1)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1a2)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1a3)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1a4)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1a5)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1a6)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1a7)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1a8)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1a9)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1aa)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1ab)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1ac)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1ad)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1ae)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1af)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1b0)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1b1)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1b2)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1b3)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1b4)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1b5)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1b6)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1b7)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1b8)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1b9)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1ba)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1bb)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1bc)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1bd)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1be)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1bf)   \
    X(car_rd,         "car_rd",         OP_CAR_RD,      0x1c0)   \
    X(rsvd,           "car_rp",         OP_CAR_RP,      0x1c1)   \
    X(rsvd,           "car_wd",         OP_CAR_WD,      0x1c2)   \
    X(rsvd,           "car_wp",         OP_CAR_WP,      0x1c3)   \
    X(cdr_rd,         "cdr_rd",         OP_CDR_RD,      0x1c4)   \
    X(rsvd,           "cdr_rp",         OP_CDR_RP,      0x1c5)   \
    X(rsvd,           "cdr_wd",         OP_CDR_WD,      0x1c6)   \
    X(rsvd,           "cdr_wp",         OP_CDR_WP,      0x1c7)   \
    X(cons_d,         "cons_d",         OP_CONS_D,      0x1c8)   \
    X(rsvd,           "cons_p",         OP_CONS_P,      0x1c9)   \
    X(uncons_d,       "uncons_d",       OP_UNCONS_D,    0x1ca)   \
    X(rsvd,           "uncons_p",       OP_UNCONS_P,    0x1cb)   \
    X(pop_d,          "pop_d",          OP_POP_D,       0x1cc)   \
    X(rsvd,           "pop_p",          OP_POP_P,       0x1cd)   \
    X(push_d,         "push_d",         OP_PUSH_D,      0x1ce)   \
    X(rsvd,           "push_p",         OP_PUSH_P,      0x1cf)   \
    X(shift_d,        "shift_d",        OP_SHIFT_D,     0x1d0)   \
    X(rsvd,           "shift_p",        OP_SHIFT_P,     0x1d1)   \
    X(unshift_d,      "unshift_d",      OP_UNSHIFT_D,   0x1d2)   \
    X(rsvd,           "unshift_p",      OP_UNSHIFT_P,   0x1d3)   \
    X(ith_rd,         "ith_rd",         OP_ITH_RD,      0x1d4)   \
    X(rsvd,           "ith_rp",         OP_ITH_RP,      0x1d5)   \
    X(rsvd,           "ith_wd",         OP_ITH_WD,      0x1d6)   \
    X(rsvd,           "ith_wp",         OP_ITH_WP,      0x1d7)   \
    X(len_d,          "len_d",          OP_LEN_D,       0x1d8)   \
    X(rsvd,           "len_p",          OP_LEN_P,       0x1d9)   \
    X(ls2lf_d,        "ls2lf_d",        OP_LS2LF_D,     0x1da)   \
    X(rsvd,           "ls2lf_p",        OP_LS2LF_P,     0x1db)   \
    X(bons_d,         "bons_d",         OP_BONS_D,      0x1dc)   \
    X(rsvd,           "bons_p",         OP_BONS_P,      0x1dd)   \
    X(split_d,        "split_d",        OP_SPLIT_D,     0x1de)   \
    X(rsvd,           "split_p",        OP_SPLIT_P,     0x1df)   \
    X(append_d,       "append_d",       OP_APPEND_D,    0x1e0)   \
    X(rsvd,           "append_p",       OP_APPEND_P,    0x1e1)   \
    X(ins_d,          "ins_d",          OP_INS_D,       0x1e2)   \
    X(rsvd,           "ins_p",          OP_INS_P,       0x1e3)   \
    X(rev_d,          "rev_d",          OP_REV_D,       0x1e4)   \
    X(rsvd,           "rev_p",          OP_REV_P,       0x1e5)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1e6)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1e7)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1e8)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1e9)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1ea)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1eb)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1ec)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1ed)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1ee)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1ef)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1f0)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1f1)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1f2)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1f3)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1f4)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1f5)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1f6)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1f7)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1f8)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1f9)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1fa)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1fb)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1fc)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1fd)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1fe)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x1ff)   \
    X(hash_md,        "hash_md",        OP_HASH_MD,     0x200)   \
    X(rsvd,           "hash_mp",        OP_HASH_MP,     0x201)   \
    X(hash_8d,        "hash_8d",        OP_HASH_8D,     0x202)   \
    X(rsvd,           "hash_8p",        OP_HASH_8P,     0x203)   \
    X(rsvd,           "phash_md",       OP_PHASH_MD,    0x204)   \
    X(rsvd,           "phash_mp",       OP_PHASH_MP,    0x205)   \
    X(rsvd,           "phash_8d",       OP_PHASH_8D,    0x206)   \
    X(rsvd,           "phash_8p",       OP_PHASH_8P,    0x207)   \
    X(newha,          "newha",          OP_NEWHA,       0x208)   \
    X(rmha_d,         "rmha_d",         OP_RMHA_D,      0x209)   \
    X(rsvd,           "rmha_p",         OP_RMHA_P,      0x20a)   \
    X(insha_d,        "insha_d",        OP_INSHA_D,     0x20b)   \
    X(rsvd,           "insha_p",        OP_INSHA_P,     0x20c)   \
    X(inskha_d,       "inskha_d",       OP_INSKHA_D,    0x20d)   \
    X(rsvd,           "inskha_p",       OP_INSKHA_P,    0x20e)   \
    X(entsha_d,       "entsha_d",       OP_ENTSHA_D,    0x20f)   \
    X(rsvd,           "entsha_p",       OP_ENTSHA_P,    0x210)   \
    X(luha_d,         "luha_d",         OP_LUHA_D,      0x211)   \
    X(rsvd,           "luha_p",         OP_LUHA_P,      0x212)   \
    X(exha_d,         "exha_d",         OP_EXHA_D,      0x213)   \
    X(rsvd,           "exha_p",         OP_EXHA_P,      0x214)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x215)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x216)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x217)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x218)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x219)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x21a)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x21b)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x21c)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x21d)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x21e)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x21f)   \
    X(eval,           "eval",           OP_EVAL,        0x220)   \
    X(times,          "times",          OP_TIMES,       0x221)   \
    X(rsvd,           "op_while",       OP_OP_WHILE,    0x222)   \
    X(loop,           "loop",           OP_LOOP,        0x223)   \
    X(each,           "each",           OP_EACH,        0x224)   \
    X(eachar,         "eachar",         OP_EACHAR,      0x225)   \
    X(rsvd,           "op_goto",        OP_OP_GOTO,     0x226)   \
    X(rsvd,           "op_if",          OP_OP_IF,       0x227)   \
    X(rsvd,           "ifte",           OP_IFTE,        0x228)   \
    X(rsvd,           "cond",           OP_COND,        0x229)   \
    X(rsvd,           "seq",            OP_SEQ,         0x22a)   \
    X(rsvd,           "alt",            OP_ALT,         0x22b)   \
    X(pass_op,        "pass",           OP_PASS,        0x22c)   \
    X(fail_op,        "fail",           OP_FAIL,        0x22d)   \
    X(rsvd,           "let",            OP_LET,         0x22e)   \
    X(die,            "die",            OP_DIE,         0x22f)   \
    X(last,           "last",           OP_LAST,        0x230)   \
    X(rsvd,           "next",           OP_NEXT,        0x231)   \
    X(iter,           "iter",           OP_ITER,        0x232)   \
    X(rsvd,           "conjure",        OP_CONJURE,     0x233)   \
    X(rsvd,           "reset",          OP_RESET,       0x234)   \
    X(babel,          "babel",          OP_BABEL,       0x235)   \
    X(root,           "root",           OP_ROOT,        0x236)   \
    X(accept_op,      "accept",         OP_ACCEPT,      0x237)   \
    X(reject_op,      "reject",         OP_REJECT,      0x238)   \
    X(return_op,      "return",         OP_RETURN,      0x239)   \
    X(babels,         "babels",         OP_RSVD,        0x23a)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x23b)   \
    X(str2num_fd,     "str2num_fd",     OP_RSVD,        0x23c)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x23d)   \
    X(num2str_fd,     "num2str_fd",     OP_RSVD,        0x23e)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x23f)   \
    X(str2ar_d,       "str2ar_d",       OP_STR2AR_D,    0x240)   \
    X(rsvd,           "str2ar_p",       OP_STR2AR_P,    0x241)   \
    X(str2num_id,     "str2num_id",     OP_STR2NUM_ID,  0x242)   \
    X(rsvd,           "str2num_ip",     OP_STR2NUM_IP,  0x243)   \
    X(str2num_d,      "str2num_d",      OP_STR2NUM_UD,  0x244)   \
    X(rsvd,           "str2num_up",     OP_STR2NUM_UP,  0x245)   \
    X(str2num_xd,     "str2num_xd",     OP_STR2NUM_XD,  0x246)   \
    X(rsvd,           "str2num_xp",     OP_STR2NUM_XP,  0x247)   \
    X(str2num_bd,     "str2num_bd",     OP_STR2NUM_BD,  0x248)   \
    X(rsvd,           "str2num_bp",     OP_STR2NUM_BP,  0x249)   \
    X(str2num_od,     "str2num_od",     OP_STR2NUM_OD,  0x24a)   \
    X(rsvd,           "str2num_op",     OP_STR2NUM_OP,  0x24b)   \
    X(num2str_id,     "num2str_id",     OP_NUM2STR_ID,  0x24c)   \
    X(rsvd,           "num2str_ip",     OP_NUM2STR_IP,  0x24d)   \
    X(num2str_d,      "num2str_d",      OP_NUM2STR_UD,  0x24e)   \
    X(rsvd,           "num2str_up",     OP_NUM2STR_UP,  0x24f)   \
    X(num2str_xd,     "num2str_xd",     OP_NUM2STR_XD,  0x250)   \
    X(rsvd,           "num2str_xp",     OP_NUM2STR_XP,  0x251)   \
    X(num2str_bd,     "num2str_bd",     OP_NUM2STR_BD,  0x252)   \
    X(rsvd,           "num2str_bp",     OP_NUM2STR_BP,  0x253)   \
    X(num2str_od,     "num2str_od",     OP_NUM2STR_OD,  0x254)   \
    X(rsvd,           "num2str_op",     OP_NUM2STR_OP,  0x255)   \
    X(rsvd,           "nl_d",           OP_NL_D,        0x256)   \
    X(rsvd,           "nl_p",           OP_NL_P,        0x257)   \
    X(rsvd,           "ord_d",          OP_ORD_D,       0x258)   \
    X(rsvd,           "ord_p",          OP_ORD_P,       0x259)   \
    X(c2b_d,          "c2b_d",          OP_CHAR_D,      0x25a)   \
    X(rsvd,           "c2b_p",          OP_CHAR_P,      0x25b)   \
    X(sprint,         "sprint",         OP_SPRINT,      0x25c)   \
    X(newstr_d,       "newstr_d",       OP_RSVD,        0x25d)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x25e)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x25f)   \
    X(sexpr,          "sexpr",          OP_RSVD,        0x260)   \
    X(bpdli_d,        "bpdli_d",        OP_BPDLI_D,     0x261)   \
    X(bpdl_d,         "bpdl_d",         OP_RSVD,        0x262)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x263)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x264)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x265)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x266)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x267)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x268)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x269)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x26a)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x26b)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x26c)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x26d)   \
    X(lusym_d,        "lusym_d",        OP_RSVD,        0x26e)   \
    X(insym_d,        "insym_d",        OP_RSVD,        0x26f)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x270)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x271)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x272)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x273)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x274)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x275)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x276)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x277)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x278)   \
    X(stdout_8d,      "stdout_8d",      OP_STDOUT_8D,   0x279)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x27a)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x27b)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x27c)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x27d)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x27e)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x27f)   \
    X(slurp_md,       "slurp_md",       OP_SLURP_MD,    0x280)   \
    X(rsvd,           "slurp_mp",       OP_SLURP_MP,    0x281)   \
    X(slurp_8d,       "slurp_8d",       OP_SLURP_8D,    0x282)   \
    X(rsvd,           "slurp_8p",       OP_SLURP_8P,    0x283)   \
    X(spit_md,        "spit_md",        OP_SPIT_MD,     0x284)   \
    X(rsvd,           "spit_mp",        OP_SPIT_MP,     0x285)   \
    X(spit_8d,        "spit_8d",        OP_SPIT_8D,     0x286)   \
    X(rsvd,           "spit_8p",        OP_SPIT_8P,     0x287)   \
    X(rsvd,           "stdout_md",      OP_STDOUT_MD,   0x288)   \
    X(rsvd,           "stdout_mp",      OP_STDOUT_MP,   0x289)   \
    X(stdout_8d,      "stdout_8d",      OP_STDOUT_8D,   0x28a)   \
    X(rsvd,           "stdout_8p",      OP_STDOUT_8P,   0x28b)   \
    X(rsvd,           "journal_md",     OP_JOURNAL_MD,  0x28c)   \
    X(rsvd,           "journal_mp",     OP_JOURNAL_MP,  0x28d)   \
    X(journal_8d,     "journal_8d",     OP_JOURNAL_8D,  0x28e)   \
    X(rsvd,           "journal_8p",     OP_JOURNAL_8P,  0x28f)   \
    X(stdinln8,       "stdinln",        OP_STDINLN,     0x290)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x291)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x292)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x293)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x294)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x295)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x296)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x297)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x298)   \
    X(deva,           "deva",           OP_RSVD,        0x299)   \
    X(dev,            "dev",            OP_RSVD,        0x29a)   \
    X(timems,         "timems",         OP_RSVD,        0x29b)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x29c)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x29d)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x29e)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x29f)   \
    X(rsvd,           "sleep_d",        OP_SLEEP_D,     0x2a0)   \
    X(rsvd,           "sleep_p",        OP_SLEEP_P,     0x2a1)   \
    X(randlf_d,       "randlf_d",       OP_RANDLF_D,    0x2a2)   \
    X(rsvd,           "randlf_p",       OP_RANDLF_P,    0x2a3)   \
    X(rsvd,           "endian",         OP_ENDIAN,      0x2a4)   \
    X(interp_exit,    "interp_exit",    OP_EXIT,        0x2a5)   \
    X(rsvd,           "hibernate",      OP_HIBERNATE,   0x2a6)   \
    X(rsvd,           "self",           OP_SELF,        0x2a7)   \
    X(fnord,          "fnord",          OP_FNORD,       0x2a8)   \
    X(rsvd,           "exec_d",         OP_EXEC_D,      0x2a9)   \
    X(rsvd,           "exec_p",         OP_EXEC_P,      0x2aa)   \
    X(rsvd,           "fork_d",         OP_FORK_D,      0x2ab)   \
    X(rsvd,           "fork_p",         OP_FORK_P,      0x2ac)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x2ad)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x2ae)   \
    X(rsvd,           "rsvd",           OP_RSVD,        0x2af)   \

//    X(rsvd,           "rsvd",           OP_RSVD,        0x000)  
//    X(rsvd,           "rsvd",           OP_RSVD,        0x000)  
//    X(stdout_8d,      "stdout_8d",      OP_STDOUT_8D,   0x001)  

    // arith opcodes:
    // bit0     -> preserve operands
    // bit1     -> operate-assign
    // bit2     -> signed

// arith-logic-compare:     0x000 - 0x0ff
// stack:                   0x100 - 0x11f
// bstruct:                 0x120 - 0x15f

#endif //OPCODE_H

// Clayton Bauman 2014

